spring:
  datasource:
    generate-unique-name: false
    name: market
    driverClassName: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
